import Head from 'next/head'
import Image from 'next/image';
import Link from 'next/link';
import styles from '../styles/Home.module.css'

export default function Home({data}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Events Pages</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <nav>
         
          <Link href="/">Home</Link>
          <Link href="/events">Events</Link>
          <Link href="/about-us">About</Link>
        </nav>
      </header>

      <main className={styles.main}>
        {data.map((ev) => (
          <Link key={ev.id} href={`/events/${ev.id}`}>
            <Image src={ev.image} alt="" height={100} width={200} />
            <h2>{ev.title}</h2>
            <p>{ev.description} </p>
          </Link>
        ))}
        <Link href="/events/london">
          <h2>Events in London</h2>
          <p>
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ipsa at
            saepe blanditiis ipsum obcaecati quaerat mollitia minima, magnam
            odit laborum autem tempore officia voluptatum ex provident sit
            numquam? Corporis fuga possimus delectus, suscipit amet itaque.
            Quibusdam, accusamus eligendi. Rem, architecto!
          </p>
        </Link>
        <a href="/events/sanfran">
          <h2>Events in San Francisco</h2>
          <p>
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ipsa at
            saepe blanditiis ipsum obcaecati quaerat mollitia minima, magnam
            odit laborum autem tempore officia voluptatum ex provident sit
            numquam? Corporis fuga possimus delectus, suscipit amet itaque.
            Quibusdam, accusamus eligendi. Rem, architecto!
          </p>
        </a>
        <a href="">
          <h2>Events in San Barcelona</h2>
          <p>
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ipsa at
            saepe blanditiis ipsum obcaecati quaerat mollitia minima, magnam
            odit laborum autem tempore officia voluptatum ex provident sit
            numquam? Corporis fuga possimus delectus, suscipit amet itaque.
            Quibusdam, accusamus eligendi. Rem, architecto!
          </p>
        </a>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}

export async function getServerSideProps() {
  const {events_categories} = await import('/data/data.json'); ;
  console.log(events_categories);
  
  return {
    props: {
      data: events_categories,
    },
  };
}
