import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Events App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={styles.main}>
        <nav>
          <img/>
          <a href="/">Home</a>
          <a href="/events">Events</a>
          <a href="/about-us">About</a>
        </nav>
      </header>

      <main className={styles.main}>
        <a href=''>
          <h2>Events in London</h2>
          <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ipsa at saepe blanditiis ipsum obcaecati quaerat mollitia minima, magnam odit laborum autem tempore officia voluptatum ex provident sit numquam? Corporis fuga possimus delectus, suscipit amet itaque. Quibusdam, accusamus eligendi. Rem, architecto!</p>
        </a>
        <a href=''>
          <h2>Events in San Francisco</h2>
          <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ipsa at saepe blanditiis ipsum obcaecati quaerat mollitia minima, magnam odit laborum autem tempore officia voluptatum ex provident sit numquam? Corporis fuga possimus delectus, suscipit amet itaque. Quibusdam, accusamus eligendi. Rem, architecto!</p>
        </a>
        <a href=''>
          <h2>Events in San Barcelona</h2>
          <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ipsa at saepe blanditiis ipsum obcaecati quaerat mollitia minima, magnam odit laborum autem tempore officia voluptatum ex provident sit numquam? Corporis fuga possimus delectus, suscipit amet itaque. Quibusdam, accusamus eligendi. Rem, architecto!</p>
        </a>
      </main>

      <footer className={styles.footer}>
        
      </footer>
    </div>
  )
}
